# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://vestalux.github.io/landing-page-theme/
title: Mentőöv
email: szia@borgiorno.hu
author: Vestalux
description: > # "Write an awesome description for your new site here.
  Mentőöv mozgó vendéglátás
copyright: 'Copyright &copy; 2021 Vestalux Szociális Szövetkezet'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:

  - title: envelope
    url: mailto:szia@borgiorno.hu
